# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2fa32d5827e0c3e55e07335a84810a8b1764ff639827f9d16d3870a2ff4be7a548cbe659e0749b0f6f0a7c3c2a88ce1845958ef736242d129f3eedb3344e0f2

test:
  secret_key_base: 7e99802416e7b1b6b0c9ab4da2829cd32479940c42abfc814d67b2f34742144b17b5181207246e6a5c6e685e40d063653794f2cc0e6881b2e91dc1c1e79bbab1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
